server:
  port: 8002

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.glide.sc.models    # 所有Entity别名类所在包


spring:
  application:
    name: cloud-dept-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/company01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      , http://localhost:7002/eureka/
  instance:
    instance-id: microservice-Dept8002
    prefer-ip-address: true