server:
  port: 8977

spring:
  application:
    name: cloud-zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/
  instance:
    instance-id: microservice-zuul-8977
    prefer-ip-address: true

zuul:
  prefix: /fbi
  ignored-services: cloud-dept-service
  routes:
    mydept.serviceId: cloud-dept-service
    mydept.path: /mydept/**