server:
  port: 8001

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.glide.sc.models    # 所有Entity别名类所在包


spring:
  application:
    name: cloud-dept-service
  #, 8.139.4.236:2182, 8.139.4.236:2183
  cloud:
    zookeeper:
      connect-string: 8.139.4.236:2181, 8.139.4.236:2182, 8.139.4.236:2183
      connectionTimeout: 20000
      max-retries: 10
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://8.139.4.236:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456