#default port of web server is 80
server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    nacos:
      discovery:
        server-addr: http://10.0.0.15:8848
        group: CloudDept
      config:
#        server-addr: http://10.0.0.15:8848
#        file-extension: yaml
#        group: CloudDept
        import-check.enabled: false
    #, 8.139.4.236:2182, 8.139.4.236:2183
#    zookeeper:
#      connect-string: 8.139.4.236:2181, 8.139.4.236:2182, 8.139.4.236:2183
#      connectionTimeout: 20000
#      max-retries: 10
#      discovery:
#        prefer-ip-address: true
#        instance-id: ${spring.cloud.client.ip-address}:${server.port}